# Generated by Django 3.1 on 2020-09-05 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_auto_20200824_1726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activeuser',
            name='room',
        ),
    ]
