# Generated by Django 3.1 on 2020-09-08 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_remove_activeuser_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='activeuser',
            name='channel',
            field=models.CharField(default=0, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activeuser',
            name='room',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='games.room'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='RPSMove',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(max_length=8)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.activeuser')),
            ],
        ),
    ]
