# Generated by Django 3.1 on 2020-09-10 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_auto_20200908_1344'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suit', models.IntegerField(choices=[(0, 'None'), (1, 'Diamond'), (2, 'Spade'), (3, 'Heart'), (4, 'Club')])),
                ('value', models.IntegerField(choices=[(0, 'Joker'), (1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five'), (6, 'Six'), (7, 'Seven'), (8, 'Eight'), (9, 'Nine'), (10, 'Ten'), (11, 'Jack'), (12, 'Queen'), (13, 'King')])),
            ],
        ),
        migrations.CreateModel(
            name='MinesweeperCell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shown', models.BooleanField(default=False)),
                ('bomb', models.BooleanField()),
                ('bombs_next', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MinesweeperBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cells', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board', to='games.minesweepercell')),
            ],
        ),
    ]
