# Generated by Django 3.1 on 2020-09-10 16:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games', '0007_card_minesweeperboard_minesweepercell'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Card',
        ),
        migrations.AddField(
            model_name='minesweeperboard',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='common.lameuser'),
            preserve_default=False,
        ),
    ]
