# Generated by Django 3.1 on 2020-09-10 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0010_auto_20200910_1809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='minesweeperboard',
            name='cells',
        ),
        migrations.AddField(
            model_name='minesweepercell',
            name='board',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='games.minesweeperboard'),
            preserve_default=False,
        ),
    ]
