# Generated by Django 3.1 on 2020-09-10 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0011_auto_20200910_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='minesweepercell',
            name='x',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='minesweepercell',
            name='y',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='minesweepercell',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='games.minesweeperboard'),
        ),
    ]
