# Generated by Django 3.1 on 2020-09-10 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0012_auto_20200910_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='minesweepercell',
            name='flagged',
            field=models.BooleanField(default=False),
        ),
    ]
