# Generated by Django 3.1 on 2020-09-10 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0014_minesweepercell_game_over'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='minesweepercell',
            name='game_over',
        ),
        migrations.AddField(
            model_name='minesweeperboard',
            name='game_over',
            field=models.BooleanField(default=False),
        ),
    ]
