# Generated by Django 3.1 on 2020-09-10 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0015_auto_20200910_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='minesweeperboard',
            name='win_lose',
            field=models.BooleanField(default=None),
        ),
    ]
