# Generated by Django 3.1 on 2020-09-10 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0016_minesweeperboard_win_lose'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='minesweeperboard',
            name='game_over',
        ),
        migrations.RemoveField(
            model_name='minesweeperboard',
            name='win_lose',
        ),
        migrations.AddField(
            model_name='minesweeperboard',
            name='status',
            field=models.IntegerField(choices=[(0, 'In Progress'), (1, 'Lost'), (2, 'Won')], default=0),
            preserve_default=False,
        ),
    ]
